-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-12-11 22:27:52 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE biuro (
    numer             NUMBER NOT NULL,
    liczbastanowisk   NUMBER NOT NULL,
    pietro            NUMBER NOT NULL,
    budynek_adres     VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE biuro ADD CONSTRAINT biuro_pk PRIMARY KEY ( numer );

CREATE TABLE budynek (
    adres           VARCHAR2(20 CHAR) NOT NULL,
    nazwa           VARCHAR2(20 CHAR) NOT NULL,
    iloscpieter     NUMBER NOT NULL,
    oddzial_adres   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE budynek ADD CONSTRAINT budynek_pk PRIMARY KEY ( adres );

CREATE TABLE dostepdobiura (
    prawdos_kartados_idkarty   NUMBER NOT NULL,
    biuro_numer                NUMBER NOT NULL
);

ALTER TABLE dostepdobiura ADD CONSTRAINT relation_6_pk PRIMARY KEY ( prawdos_kartados_idkarty,
                                                                     biuro_numer );

CREATE TABLE dzial (
    nazwa           VARCHAR2(20 CHAR) NOT NULL,
    skrot           VARCHAR2(5 CHAR) NOT NULL,
    oddzial_adres   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE dzial ADD CONSTRAINT dzial_pk PRIMARY KEY ( nazwa );

CREATE TABLE kartadostepu (
    idkarty           NUMBER NOT NULL,
    dataprzyznania    DATE NOT NULL,
    pracownik_pesel   VARCHAR2(11 CHAR) NOT NULL
);

CREATE UNIQUE INDEX kartadostepu__idx ON
    kartadostepu (
        pracownik_pesel
    ASC );

ALTER TABLE kartadostepu ADD CONSTRAINT kartadostepu_pk PRIMARY KEY ( idkarty );

CREATE TABLE magazyn (
    numer           NUMBER NOT NULL,
    pojemnosc       NUMBER NOT NULL,
    oddzial_adres   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE magazyn ADD CONSTRAINT magazyn_pk PRIMARY KEY ( numer );

CREATE TABLE oddzial (
    adres   VARCHAR2(20 CHAR) NOT NULL,
    nazwa   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE oddzial ADD CONSTRAINT oddzial_pk PRIMARY KEY ( adres );

CREATE TABLE oprogramowanie (
    numerewidencyjny   NUMBER NOT NULL,
    nazwa              VARCHAR2(30 CHAR) NOT NULL,
    producent          VARCHAR2(20 CHAR) NOT NULL,
    datazakupu         DATE NOT NULL,
    datawygasniecia    DATE,
    ilosclicencji      NUMBER,
    uwagi              VARCHAR2(150 CHAR)
);

ALTER TABLE oprogramowanie ADD CONSTRAINT oprogramowanie_pk PRIMARY KEY ( numerewidencyjny );

CREATE TABLE oprogramowanienasprzecie (
    sprzet_numer           NUMBER NOT NULL,
    oprogramowanie_numer   NUMBER NOT NULL
);

ALTER TABLE oprogramowanienasprzecie ADD CONSTRAINT relation_10_pk PRIMARY KEY ( sprzet_numer,
                                                                                 oprogramowanie_numer );

CREATE TABLE pracownik (
    pesel             VARCHAR2(11 CHAR) NOT NULL,
    imie              VARCHAR2(20 CHAR) NOT NULL,
    nazwisko          VARCHAR2(20 CHAR) NOT NULL,
    numertelefonu     VARCHAR2(9 CHAR) NOT NULL,
    czynadalpracuje   CHAR(1) NOT NULL,
    adresemail        VARCHAR2(30 CHAR) NOT NULL,
    dzial_nazwa       VARCHAR2(20 CHAR) NOT NULL,
    biuro_numer       NUMBER NOT NULL
);

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( pesel );

CREATE TABLE prawodostepu (
    dataprzyznania         DATE NOT NULL,
    datawygasniecia        DATE NOT NULL,
    kartadostepu_idkarty   NUMBER NOT NULL
);

ALTER TABLE prawodostepu ADD CONSTRAINT prawodostepu_pk PRIMARY KEY ( kartadostepu_idkarty );

CREATE TABLE przypisanie (
    idprzydzialu      NUMBER NOT NULL,
    dataprzydzialu    DATE NOT NULL,
    terminzwrotu      DATE,
    pracownik_pesel   VARCHAR2(11 CHAR),
    biuro_numer       NUMBER
);

ALTER TABLE przypisanie ADD CONSTRAINT przypisanie_pk PRIMARY KEY ( idprzydzialu );

CREATE TABLE sprzet (
    numerewidencyjny   NUMBER NOT NULL,
    datazakupu         DATE NOT NULL,
    nazwa              VARCHAR2(30 CHAR) NOT NULL,
    typ                VARCHAR2(20 CHAR) NOT NULL,
    producent          VARCHAR2(20 CHAR) NOT NULL,
    uwagi              VARCHAR2(150 CHAR),
    magazyn_numer      NUMBER
);

ALTER TABLE sprzet ADD CONSTRAINT sprzet_pk PRIMARY KEY ( numerewidencyjny );

CREATE TABLE sprzetwprzypisaniu (
    sprzet_numerewidencyjny    NUMBER NOT NULL,
    przypisanie_idprzydzialu   NUMBER NOT NULL
);

ALTER TABLE sprzetwprzypisaniu ADD CONSTRAINT sprzetwprzypisaniu_pk PRIMARY KEY ( sprzet_numerewidencyjny,
                                                                                  przypisanie_idprzydzialu );

ALTER TABLE biuro
    ADD CONSTRAINT biuro_budynek_fk FOREIGN KEY ( budynek_adres )
        REFERENCES budynek ( adres );

ALTER TABLE budynek
    ADD CONSTRAINT budynek_oddzial_fk FOREIGN KEY ( oddzial_adres )
        REFERENCES oddzial ( adres );

ALTER TABLE dostepdobiura
    ADD CONSTRAINT dostepdobiura_biuro_fk FOREIGN KEY ( biuro_numer )
        REFERENCES biuro ( numer );

ALTER TABLE dostepdobiura
    ADD CONSTRAINT dostepdobiura_prawodostepu_fk FOREIGN KEY ( prawdos_kartados_idkarty )
        REFERENCES prawodostepu ( kartadostepu_idkarty );

ALTER TABLE dzial
    ADD CONSTRAINT dzial_oddzial_fk FOREIGN KEY ( oddzial_adres )
        REFERENCES oddzial ( adres );

ALTER TABLE kartadostepu
    ADD CONSTRAINT kartadostepu_pracownik_fk FOREIGN KEY ( pracownik_pesel )
        REFERENCES pracownik ( pesel );

ALTER TABLE magazyn
    ADD CONSTRAINT magazyn_oddzial_fk FOREIGN KEY ( oddzial_adres )
        REFERENCES oddzial ( adres );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_biuro_fk FOREIGN KEY ( biuro_numer )
        REFERENCES biuro ( numer );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_dzial_fk FOREIGN KEY ( dzial_nazwa )
        REFERENCES dzial ( nazwa );

ALTER TABLE prawodostepu
    ADD CONSTRAINT prawodostepu_kartadostepu_fk FOREIGN KEY ( kartadostepu_idkarty )
        REFERENCES kartadostepu ( idkarty );

ALTER TABLE przypisanie
    ADD CONSTRAINT przypisanie_biuro_fk FOREIGN KEY ( biuro_numer )
        REFERENCES biuro ( numer );

ALTER TABLE przypisanie
    ADD CONSTRAINT przypisanie_pracownik_fk FOREIGN KEY ( pracownik_pesel )
        REFERENCES pracownik ( pesel );

ALTER TABLE oprogramowanienasprzecie
    ADD CONSTRAINT relation_10_oprogramowanie_fk FOREIGN KEY ( oprogramowanie_numer )
        REFERENCES oprogramowanie ( numerewidencyjny );

ALTER TABLE oprogramowanienasprzecie
    ADD CONSTRAINT relation_10_sprzet_fk FOREIGN KEY ( sprzet_numer )
        REFERENCES sprzet ( numerewidencyjny );

ALTER TABLE sprzetwprzypisaniu
    ADD CONSTRAINT sprwprzyp_przypisanie_fk FOREIGN KEY ( przypisanie_idprzydzialu )
        REFERENCES przypisanie ( idprzydzialu );

ALTER TABLE sprzetwprzypisaniu
    ADD CONSTRAINT sprwprzyp_sprzet_fk FOREIGN KEY ( sprzet_numerewidencyjny )
        REFERENCES sprzet ( numerewidencyjny );

ALTER TABLE sprzet
    ADD CONSTRAINT sprzet_magazyn_fk FOREIGN KEY ( magazyn_numer )
        REFERENCES magazyn ( numer );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             1
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
